services:
  proxy:
    image: caddy:2.7.4-alpine
    ports:
      - 80:80
      - 443:443
      - 8443:8443
      - 9980:9980
    volumes:
      - caddy_data:/data
      - caddy_config:/config
      - type: bind
        source: ./Caddyfile
        target: /etc/caddy/Caddyfile

volumes:
  caddy_data:
    external: true
  caddy_config:
