services:
  overclicked:
    image: ghcr.io/clicepfl/overclicked:main
    environment:
      # Change this only if sure that the new directory has the proper permissions
      OVERCLICKED_DB_DIR: "/db"
      OVERCLICKED_PASSWORD: ${OVERCLICKED_PASSWORD}
    volumes:
      - "db:/db"
    ports:
      - 8023:3000

volumes:
  db:
